language: python
python:
  - "3.5"
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
install:
  - pip install --upgrade pip wheel setuptools coverage codecov django_coverage_plugin tox
script: tox
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test
after_success:
  - coverage xml
  - codecov
notifications:
  email: false
cache:
  apt: true
  pip: true

