language: python
python:
  - "3.5"
install:
  - pip install tox
script: tox
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URL=postgres://postgres:postgres@postgres:5432/travis_ci_test
after_success:
  - codecov
notifications:
  email: false
