# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20161217_1825'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='point',
        ),
        migrations.AddField(
            model_name='story',
            name='point',
            field=models.ManyToManyField(to='points.Point'),
        ),
    ]
