# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20161217_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='point',
            new_name='points',
        ),
    ]
