# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 11:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20170304_1157'),
        ('stories', '0003_auto_20161217_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='first_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_point', to='points.Point'),
        ),
    ]
