# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_image',
        ),
    ]
