# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_story_image'),
        ('points', '0007_remove_point_images'),
        ('images', '0002_image_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_images', to='points.Point'),
        ),
        migrations.AddField(
            model_name='image',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_images', to='stories.Story'),
        ),
    ]
