# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 20:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('points', '0002_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
