# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('points', '0003_point_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='image',
        ),
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
