# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20170304_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='images',
        ),
    ]
